# Generated by Django 2.0.2 on 2018-03-17 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('position', models.IntegerField(default=0, unique=True)),
                ('title', models.CharField(default='', max_length=100)),
                ('frame_type', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FrameType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=0)),
                ('max', models.IntegerField(default=0)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='me_api.Frame')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='me_api.Frame')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='picture',
            unique_together={('frame', 'position')},
        ),
    ]
