# Generated by Django 2.0.2 on 2018-04-07 10:12

from django.db import migrations, models
import django.db.models.deletion
import me_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('me_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to=me_api.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='picture',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='me_api.Frame'),
        ),
    ]
