# Generated by Django 2.0.2 on 2018-04-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me_api', '0003_remove_picture_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='frame',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
